### ISSUE TITLE
I CANT GET REDSTONE

### ISSUE THREAD

**Issue by Askalotll** [MrRedstoneToGo/Create-Bamboo-Island#1]
HOW DO YOU GET REDSTONE I COULDNT FIGURE IT OUT AND I FOUND NOTHING ON THE INTERNET I DONT THINK THERE IS A ISSUE WITH THE MODOACK I JUST DIDNT KNOW WHERE ELSE I COULD ASK

REGARDS
ME

**Comment by MrRedstoneToGo** [comment]
Have you ever thought about spouting Cinder Flour with a Strength Potion? That's what it says in EMI (on the second page). You can get Netherwarts for brewing by growing Crimson Fungus and milling the leaves (Netherwarts blocks).
