### ISSUE TITLE
Help, Don't know how to get netherwort or redstone

### ISSUE THREAD

**Issue by Dalton-Wither** [MrRedstoneToGo/Create-Bamboo-Island#3]
I can't find a way to get redstone.
autocrafters require rose quartz & I can't make it.
Piglins aren't giving netherwort which I could use to make redstone through brewing & spout either.

Am I missing something or is there no way to progress without cheating?
Just in case I can make a suggestion if there is no way to get it, maybe I could mix 8 red sand & a fire charge in a basin for it?

**Comment by MrRedstoneToGo** [comment]
Somebody else reported this already and the problem is solved for him now:h
ttps://github.com/MrRedstoneToGo/Create-Bamboo-Island/issues/1

**Comment by Dalton-Wither** [comment]
Oh I'm sorry, new Minecraft versions are so cool
