### ISSUE TITLE
(feat) QOL add-on Kleeslabs and Hide Experimental Warning,

### ISSUE THREAD

**Issue by denzuko** [MrRedstoneToGo/Create-Bamboo-Island#5]
First off  would love to say I absolutely love this pack, its very well balanced and hits Skyblock right on the nose.

I'm sure there's a lot out there that would love to see a FTB like skyblock feature added but I build packs like this too and would like to suggest adding:

* [Hide Experimental Warning](https://modrinth.com/mod/hide-experimental-warning): Removes the warning that pops up doing loading a world 
* [Kleeslabs](https://modrinth.com/mod/kleeslabs): since Minecraft should allow a user to break only one half of a double slab without having to replace the whole block. Helpful for when bridging over the void.

Kleeslabs and Hide Experimental Warnings are really good QOL mods that don't change the game's flow or balance so would be nice to have in the pack.

**Comment by MrRedstoneToGo** [comment]
No, I meant whether a Mechanical Drill destroys only one slab of a double slab, and as it turned out, it always destroys both. But that's not so bad.

**Comment by MrRedstoneToGo** [comment]
If you want to contribute something and are good at building, it would be really cool if you could help build the world for the trailer, the technology is already there, now it's just a matter of decorating it (which I'm not that good at). The only small problem is the 6 hour time difference (12:00 p.m. for you is 6:00 p.m. for me). See when you have time.
