### ISSUE TITLE
Impossible to get redstone

### ISSUE THREAD

**Issue by Warrio20** [MrRedstoneToGo/Create-Bamboo-Island#7]
To achieve "Make quartz a bit rosy" you need redstone, but it's impossible to get redstone without nether wart (Nether wart impossible to get too)

**Comment by Warrio20** [comment]
And dont know how to get red mushrooms

**Comment by MrRedstoneToGo** [comment]
Firstly, you need a Sniffer that digs up a Mooshroom Spawn Egg. This allows you to spawn a Mooshroom (these special cows) and shear it (preferably if you have several). You can haunt the (red) Mushrooms into Crimson Fungus, grow them, harvest the Nether Wart blocks and then throw them into a Millstone. And then you have your Nether Warts. Any questions?

**Comment by Warrio20** [comment]
Oh, ok, thanks
